
//generated by src/scripts/write-version-info.sh
package org.apache.sqoop;

public class SqoopVersion {
  public SqoopVersion() {
  }

  public static final String VERSION="1.4.3";
  public static final String GIT_HASH="dummy-git-hash";
  public static final String COMPILE_USER="dspeer";
  public static final String COMPILE_DATE="6/24/2013";

  @Override
  public String toString() {
    return "Sqoop " + VERSION + "\n"
        + "git commit id " + GIT_HASH + "\n"
        + "Compiled by " + COMPILE_USER
        + " on " + COMPILE_DATE + "\n";
  }
}